services:
  inference:
    build: .
    image: crab-detection-codetr:latest
    env_file:
      - .env
    volumes:
      # Mount local data, src, and config into /app
      - ./data:/app/data
      - ./src:/app/src
      - ./config.default.yaml:/app/config.default.yaml:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["/app/.venv/bin/python", "-m", "src.app.visualize_inference"]
