[project]
name = "Crab-Detection-CODETR"
version = "0.1.0"
description = "Self-contained Dockerized inference for CO-DETR crab detection."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "torchvision",
    "python-dotenv",
    "PyYAML",
    "opencv-python<4.10.0",
    "pandas>=2.3.3",
    "sahi>=0.11.36",
    "numpy<2",
    "mmcv>=2.1.0, <2.2.0",
    "mmdet>=3.3.0",
    "tqdm",
    "setuptools<70"
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv.extra-build-dependencies]
mmcv = ["setuptools<70", "wheel", "torch", "numpy", "cython"]

[tool.setuptools.packages.find]
include = ["src*"]