# Auto-generated Co-DETR (Co-DINO) config for crab detection — Version 1.2.3
# Generated by: uv run python -m cangrejo.app.v1_2_4.co_detr_config
#
# To train:
#   sbatch cangrejo/tramuntana/v1_2_4/train_co_detr.slurm

# Use the absolute path to the MMDetection repository cloned by the slurm script
_base_ = [
    '/app/mmdetection/projects/CO-DETR/configs/codino/co_dino_5scale_swin_l_16xb1_1x_coco.py',
]

custom_imports = dict(
    imports=['projects.CO-DETR.codetr'], allow_failed_imports=False)

num_dec_layer = 6
loss_lambda = 2.0

# ── Model ──────────────────────────────────────────────────────────────
model = dict(
    query_head=dict(
        num_classes=1,
    ),
    roi_head=[
        dict(
            type='CoStandardRoIHead',
            bbox_roi_extractor=dict(
                type='SingleRoIExtractor',
                roi_layer=dict(
                    type='RoIAlign', output_size=7, sampling_ratio=0),
                out_channels=256,
                featmap_strides=[4, 8, 16, 32, 64],
                finest_scale=56),
            bbox_head=dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=False,
                reg_decoded_bbox=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=5.0 * num_dec_layer * loss_lambda),
                loss_bbox=dict(
                    type='GIoULoss',
                    loss_weight=5.0 * num_dec_layer * loss_lambda)))
    ],
    bbox_head=[
        dict(
            type='CoATSSHead',
            num_classes=1,
            in_channels=256,
            stacked_convs=1,
            feat_channels=256,
            anchor_generator=dict(
                type='AnchorGenerator',
                ratios=[1.0],
                octave_base_scale=8,
                scales_per_octave=1,
                strides=[4, 8, 16, 32, 64, 128]),
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[.0, .0, .0, .0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            loss_cls=dict(
                type='FocalLoss',
                use_sigmoid=True,
                gamma=2.0,
                alpha=0.25,
                loss_weight=2.0 * num_dec_layer * loss_lambda),
            loss_bbox=dict(
                type='GIoULoss',
                loss_weight=2.0 * num_dec_layer * loss_lambda),
            loss_centerness=dict(
                type='CrossEntropyLoss',
                use_sigmoid=True,
                loss_weight=1.0 * num_dec_layer * loss_lambda)),
    ],
)

# ── Dataset ────────────────────────────────────────────────────────────
data_root = '/app/data/codetr_tiling_multicrop'
metainfo = dict(classes=('crab', ))

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', scale=(1000, 1000), keep_ratio=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'))
]

train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file=data_root + '/annotations/instances_train.json',
        data_prefix=dict(img='train/images/'),
        metainfo=metainfo,
        pipeline=train_pipeline
    )
)

val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file=data_root + '/annotations/instances_valid.json',
        data_prefix=dict(img='valid/images/'),
        metainfo=metainfo,
        pipeline=test_pipeline
    )
)

test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file=data_root + '/annotations/instances_test.json',
        data_prefix=dict(img='test/images/'),
        metainfo=metainfo,
        pipeline=test_pipeline
    )
)

val_evaluator = dict(
    ann_file=data_root + '/annotations/instances_valid.json',
)

test_evaluator = dict(
    ann_file=data_root + '/annotations/instances_test.json',
)

# ── Training schedule ──────────────────────────────────────────────────
max_epochs = 36

train_cfg = dict(
    type='EpochBasedTrainLoop',
    max_epochs=max_epochs,
    val_interval=1,
)

# Learning rate — smaller for fine-tuning
optim_wrapper = dict(
    optimizer=dict(lr=0.0001),
)

# Cosine Annealing LR
param_scheduler = [
    dict(
        type='CosineAnnealingLR',
        begin=0,
        T_max=max_epochs,
        end=max_epochs,
        by_epoch=True,
        eta_min=1e-6
    )
]

# ── Pretrained weights ─────────────────────────────────────────────────
load_from = 'https://huggingface.co/maverickrzw/co-detr-pth/resolve/main/co_dino_5scale_swin_large_22e_o365.pth'

# ── Runtime ────────────────────────────────────────────────────────────
default_hooks = dict(
    checkpoint=dict(type='CheckpointHook', interval=1, max_keep_ckpts=3, save_best='coco/bbox_mAP_50', rule='greater'),
    logger=dict(type='LoggerHook', interval=50),
)

custom_hooks = []



# ── Work directory ─────────────────────────────────────────────────────
work_dir = '/app/data/results/modelsOrCheckpoints'
